name: "virtual_job_fair_platform_production"

services:
  rails-app:
    image: wahab457/virtual_job_fair_platform:latest
    environment:
      - RAILS_MASTER_KEY
      - DB_HOST=postgres
      - chrome_launchOptions_protocolTimeout=600000
    ports:
    - 3000:3000
    depends_on: 
    - redis
    - postgres

  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
    - redis-data:/data

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"

volumes:
  redis-data:
  postgres-data:
