name: Build, Push, and Deploy Rails App

on:
  push:
    branches:
      - cleanup/v1

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image
        run: |
          docker build -t wahab457/virtual_job_fair_platform:latest .

      - name: Push image to Docker Hub
        run: |
          docker push wahab457/virtual_job_fair_platform:latest

      - name: Copy docker-compose.yaml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.yaml"
          target: "/home/jobfair/"

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          scp: 'docker-compose.yaml:/home/jobfair/'
          script: |
            cd /home/jobfair/
            docker compose down || true
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} docker compose up -d
